parent(pam,bob).
parent(tom,bob).
parent(tom,liz).
parent(bob,ann).
parent(bob,pat).
parent(pat,jim).
parent(joe,jim).
male(tom).
male(bob).
male(jim).
male(joe).
female(pam).
female(ann).
female(liz).
female(pat).
grandparent(X,Y):-parent(X,M),parent(M,Y).
child(X,Y):-parent(Y,X).
son(X,Y):-child(X,Y),male(X).
granddaughter(X,Y):-female(X),grandparent(Y,X).
aunt(X,Y):-female(X),grandparent(M,Y),parent(M,X),not(parent(X,Y)).
partner(X,Y):-parent(X,M),parent(Y,M),not(X=Y).